version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    environment:
      - PYTHONUNBUFFERED=1
      - TABLE_NAME=MyTable-dev
      - AWS_PROFILE=default
      - AWS_REGION_NAME=us-east-1
      - AWS_COGNITO_APP_CLIENT_ID=6ib0lefeskn33ugk4nc08uqtt7
      - AWS_COGNITO_USER_POOL_ID=us-east-1_ETXEnpSV3
    restart: unless-stopped 